name: Upstream Sync and Cleanup

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"  # 每天执行
  workflow_dispatch:

jobs:
  sync_and_cleanup:
    name: Sync upstream branch and cleanup old branches
    runs-on: ubuntu-latest
    # if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: 检出当前仓库
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: 同步上游仓库指定分支
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: Eltirosto/Degrees-of-Lewdity-Chinese-Localization   # ← 修改这里
          upstream_sync_branch: gh-pages                  # ← 上游分支
          target_sync_branch: gh-pages                    # ← 你要同步到的分支
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      # Step 3: 删除三年未更新的分支
      - name: Delete branches not updated in 3 years
        run: |
          git fetch --all --prune
          THREE_YEARS_AGO=$(date -d "3 years ago" +%s)
          PROTECTED_BRANCHES=("main" "master" "gh-pages")
          echo "开始检查旧分支……"
          for BRANCH in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/); do
            BRANCH_NAME=${BRANCH#origin/}
            if [[ " ${PROTECTED_BRANCHES[*]} " == *" $BRANCH_NAME "* ]]; then
              continue
            fi
            LAST_COMMIT_DATE=$(git log -1 --format=%ct origin/$BRANCH_NAME)
            if [ $LAST_COMMIT_DATE -lt $THREE_YEARS_AGO ]; then
              echo "删除旧分支: $BRANCH_NAME"
              git push origin --delete $BRANCH_NAME || true
            fi
          done
          echo "清理完成。"

      # Step 4: 失败提示
      - name: Sync check
        if: failure()
        run: |
          echo "[Error] 上游仓库 workflow 文件变更导致同步失败，请手动执行 Sync Fork。"
          # exit 1
